server:
  port: ${PORT} 
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:techacademyit/repo-config.git
          ignoreLocalSshSettings: true
          privateKey: ${PRIVATE_KEY}